# disable sudo for container build.
sudo: required

# Enabling test on Linux and OS X
os:
  - linux
  - osx

osx_image: xcode8

group: deprecated-2017Q4

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    # Code lint
    - TASK=lint
    # Python tests
    - TASK=python_test
    # C++ tests
    - TASK=cpp_test

matrix:
  exclude:
  - os: osx
    env: TASK=lint
  - os: osx
    env: TASK=cpp_test

# dependent apt packages
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8
      - clang-3.4
      - lcov

before_install:
  - source dmlc-core/scripts/travis/travis_setup_env.sh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python

install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

before_cache:
  - dmlc-core/scripts/travis/travis_before_cache.sh

notifications:
  email:
    on_success: change
    on_failure: always
