name: coverage-tests

on:
  pull_request:
  push:
  schedule:
    - cron: "0 7 * * *"  # Run once daily

permissions:
  contents: read  # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CODECOV_TOKEN: afe9868c-2c27-4853-89fa-4bc5d3d2b255

jobs:
  cpp-python-coverage:
    name: Run Python and C++ tests with test coverage (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: dev
        environment-file: ops/conda_env/dev.yml
        use-mamba: true
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Run tests with test coverage computation
      run: |
        bash ops/cpp-python-coverage.sh
  win-python-coverage:
    name: Run Python and C++ tests with test coverage (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: dev
        environment-file: ops/conda_env/dev.yml
        use-mamba: true
    - name: Display Conda env
      shell: cmd /C CALL {0}
      run: |
        conda info
        conda list
    - name: Run tests with test coverage computation
      shell: cmd /C CALL {0}
      run: |
        call ops/win-python-coverage.bat
  macos-python-coverage:
    name: Run Python and C++ tests with test coverage (MacOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: dev
        environment-file: ops/conda_env/dev.yml
        use-mamba: true
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Run tests with test coverage computation
      run: |
        bash ops/macos-python-coverage.sh
